### ISSUE TITLE
Just some inconsistencies.

### ISSUE THREAD

**Issue by KaJe5380** [G4PLS/AudioControl#4]
YouTube videos (just click the image, it should open the video)

When using audio control plugin's dial control, the volume can somehow bypass KDE's own maximum volume. This is weird as using the dial control on my keyboard (Keychron Q8) it does not.

[![Volume controls inconsistencies](http://img.youtube.com/vi/SHQo4jmxx60/0.jpg)](http://www.youtube.com/watch?v=SHQo4jmxx60 "Volume controls inconsistencies")

When muting with my keyboard, KDE will show popup of the audio being muted. However when muting with the plugin, it somehow does a stealth mute.
However when adjusting the audio with the plugin, it does pop up the notification?
[![Volume controls inconsistencies](http://img.youtube.com/vi/WKnyeS5UyZs/0.jpg)](http://www.youtube.com/watch?v=WKnyeS5UyZs "Audio muting inconsistent")

Not a ground breaking bug, but it would be nice if it followed closer to how regular StreamDeck software on Windows works.

Here is my linux outputted via FastFetch within Konsole:
![image](https://github.com/user-attachments/assets/bd54b69a-024a-487b-8e88-704c503f505e)

**Comment by G4PLS** [comment]
Some things are weird with KDE.
For example changing the Volume in general may completely confuse KDE and doesnt make it display the Correct volume like in this Image:
![image](https://github.com/user-attachments/assets/d59ac921-207a-4f21-8051-c07b81fe527b)

But those display Bugs are purely from KDE and they appear because I interact with Pulse directly. That is why when you check volumes or mute status with pulsectl everything matches. And those graphical "bugs" are nothing that I can really change.

I will add a function that limits the Volume adjustment. So for exmaple you can set it up to only increase volume when under 50% or in your case 100%. Currently you can increase volume further than 100% because Pulse is able to do that and can boost the volume, but i understand that this may be confusing

**Comment by G4PLS** [comment]
The Volume bounds are now added with 46bc1b56f3cf03616f98a1b4ac1a90aaf3ec496a and are awaiting merge with: https://github.com/StreamController/StreamController-Store/pull/46
